import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export async function generatePDF(element: HTMLElement, taskName: string): Promise<void> {
  if (!element) return;

  const now = new Date();
  const dateStr = `${now.getFullYear()}${String(now.getMonth() + 1).padStart(2, '0')}${String(now.getDate()).padStart(2, '0')}`;
  const fileName = `微磁学报告_${taskName}_${dateStr}.pdf`;

  const reportDate = now.toLocaleDateString('zh-CN', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  const canvas = await html2canvas(element, {
    scale: 2,
    useCORS: true,
    allowTaint: true,
    backgroundColor: '#0A1628',
    logging: false,
    windowWidth: element.scrollWidth,
    windowHeight: element.scrollHeight
  });

  const imgData = canvas.toDataURL('image/png');
  const imgWidth = canvas.width;
  const imgHeight = canvas.height;

  const pdf = new jsPDF({
    orientation: imgWidth > imgHeight ? 'landscape' : 'portrait',
    unit: 'px',
    format: [imgWidth + 80, imgHeight + 120]
  });

  pdf.setFillColor(10, 22, 40);
  pdf.rect(0, 0, pdf.internal.pageSize.getWidth(), pdf.internal.pageSize.getHeight(), 'F');

  pdf.setTextColor(241, 245, 249);
  pdf.setFontSize(22);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Micromagnetics Simulation Report', 40, 45);

  pdf.setTextColor(148, 163, 184);
  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'normal');
  pdf.text(`\u5FAE\u78C1\u5B66\u6A21\u62DF\u5B8C\u6574\u62A5\u544A | Task: ${taskName}`, 40, 62);
  pdf.text(`Date: ${reportDate}`, 40, 78);

  pdf.setDrawColor(59, 130, 246);
  pdf.setLineWidth(0.5);
  pdf.line(40, 92, pdf.internal.pageSize.getWidth() - 40, 92);

  pdf.addImage(imgData, 'PNG', 40, 100, imgWidth, imgHeight);

  const pageHeight = pdf.internal.pageSize.getHeight();
  pdf.setTextColor(100, 116, 139);
  pdf.setFontSize(9);
  pdf.text(
    `Generated by Micromagnetics Simulation Platform | Page ${pdf.getNumberOfPages()}`,
    pdf.internal.pageSize.getWidth() / 2,
    pageHeight - 25,
    { align: 'center' }
  );

  pdf.save(fileName);
}
